name: Feature request
description: Create a feature request.
title: "feat: "
labels: ["feat"]
type: feature
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature
    attributes:
      label: What do you want to request?
      description: Feel free to give suggestions on how we might implement this?
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our Code of Conduct, see
        CODE_OF_CONDUCT.md for more details.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: no-similar
    attributes:
      label: No similar issues
      description: >
        I've searched for similar issues and found no issues that described the
        same issues as this one
      options:
        - label: I've searched for similar issues and found none.
          required: true
