name: "Lint PR title"

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: ! (endsWith(github.actor, '[bot]') || endsWith(github.actor, 'bot') || contains(github.actor, 'renovate'))
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
