name: conventional-commits

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  conventional:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enforce Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,test,docs,deps,ci,refactor,perf,style,build,chore,revert"
