name: Enforce branch naming

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
        ref="${{ github.ref }}"
        branch="${ref#refs/heads/}"

        allowed_branch_names=$(\cat .github/labeler.yml | yq 'to_entries[]
          | .value
          | .[]
          | select(has("head-branch"))
          | .[]
          | .[]
          ')

        echo "Allowed branch names are: "
        echo "$allowed_branch_names"
        echo ""

        for pattern in $allowed_branch_names; do
          pattern=$(echo "$pattern" | sed 's|\\\\/|/|g' | sed 's|\"||g')
          matches=$(echo "$branch" | grep --extended-regexp "$pattern" --count --no-messages || true)
          if [[ $matches -eq 1 ]]; then
            echo "Matched: $pattern"
            exit 0
          fi
        done

        echo "No match found"
        exit 1