on: pull_request_target

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.1
        with:
          script: |
            
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })

            const issues = await github.paginate(opts)

            for (const issue of issues) {
              if (issue.number === context.issue.number) continue;
              if (issue.pull_request) return; // Creator is already a contributor.
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, new contributor!

                Thank you for your PR. Please make sure you've read our [contributing guide](CONTRIBUTING.md). We look forward to reviewing your Pull request shortly ✨`
            })