name: No capital extensions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Search for .capitalized files
        run: |
          echo "Looking for files with capital extensions..."

          # skip .git, and vendor directories
          matches=$(find . \
            -path ./.git -prune -o \
            -path ./node_modules -prune -o \
            -path ./vendor -prune -o \
            -type f -print | grep -E '\.[A-Z]+$' || true)
          if [ -n "$matches" ]; then
            echo "ERROR: Found files with capitalized extensions:"
            echo ""
            echo "$matches"
            echo ""
            echo "Please change the extension to something that isn't capitalized."
            exit 1
          else
            echo "No .MD files found."
          fi
