name: no-dead-links

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]
  schedule: [cron: "0 0 * * 0"]

jobs:

  no-dead-links:
    name: No dead links
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check the links
        uses: lycheeverse/lychee-action@v2
        with:
          args: -v --max-concurrency 1 **/*.md 
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
