name: no-merge-commits

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  no-merge-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test
        uses: NexusPHP/no-merge-commits@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
