name: update-changelog

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:

  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .config/changelog.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Commit changelog
        run: |
          branch="main"
          git checkout $branch
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit --message "docs(changelog): Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $branch
